---
apiVersion: mirror.openshift.io/v1alpha2
kind: ImageSetConfiguration
storageConfig:
  local:
    path: ./
mirror:
  platform:
    channels: []
    graph: true
  operators: []
  additionalImages: []
